using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Flags : MonoBehaviour
{

    [SerializeField]
    List<string> flag = new();

    

    // Start is called before the first frame update 
    void Start()
    {
        flag.Add("Afghanistan");
        flag.Add("Albania");
        flag.Add("Algeria");
        flag.Add("American Samoa");
        flag.Add("Andorra");
        flag.Add("Angola");
        flag.Add("Anguilla");
        flag.Add("Antarctica");
        flag.Add("Antigua and Barbuda");
        flag.Add("Argentina");
        flag.Add("Armenia");
        flag.Add("Aruba");
        flag.Add("Australia");
        flag.Add("Austria");
        flag.Add("Azerbaijan");
        flag.Add("Bahrain");
        flag.Add("Bangladesh");
        flag.Add("Barbados");
        flag.Add("Belarus");
        flag.Add("Belgium");
        flag.Add("Belize");
        flag.Add("Benin");
        flag.Add("Bermuda");
        flag.Add("Bhutan");
        flag.Add("Bolivia");
        flag.Add("Bosnia");
        flag.Add("Botswana");
        flag.Add("Bouvet Island");
        flag.Add("Brazil");
        flag.Add("Brunei");
        flag.Add("Bulgaria");
        flag.Add("Burkina Faso");
        flag.Add("Burundi");
        flag.Add("Cambodia");
        flag.Add("Cameroon");
        flag.Add("Canada");
        flag.Add("Cape Verde");
        flag.Add("Caribbean Netherlands");
        flag.Add("Cayman Islands");
        flag.Add("Central African Republic");
        flag.Add("Chad");
        flag.Add("Chile");
        flag.Add("China");
        flag.Add("Christmas Island");
        flag.Add("Cocos (Keeling) Islands");
        flag.Add("Colombia");
        flag.Add("Cook Islands");
        flag.Add("Costa Rica");
        flag.Add("Croatia");
        flag.Add("Cuba");
        flag.Add("Curacao");
        flag.Add("Cyprus");
        flag.Add("Czech Republic");
        flag.Add("Democratic Republic of the Congo");
        flag.Add("Denmark");
        flag.Add("Djibouti");
        flag.Add("Dominica");
        flag.Add("Dominican Republic");
        flag.Add("Ecuador");
        flag.Add("Egypt");
        flag.Add("El Salvador");
        flag.Add("England");
        flag.Add("Equatorial Guinea");
        flag.Add("Eritrea");
        flag.Add("Estonia");
        flag.Add("Ethiopia");
        flag.Add("Falkland Islands");
        flag.Add("Faroe Islands");
        flag.Add("Fiji");
        flag.Add("Finland");
        flag.Add("France");
        flag.Add("French Guiana");
        flag.Add("French Polynesia");
        flag.Add("French Southern and Antarctic Lands");
        flag.Add("Gabon");
        flag.Add("Gambia");
        flag.Add("Georgia");
        flag.Add("Germany");
        flag.Add("Ghana");
        flag.Add("Gibraltar");
        flag.Add("Greece");
        flag.Add("Greenland");
        flag.Add("Grenada");
        flag.Add("Guadeloupe");
        flag.Add("Guam");
        flag.Add("Guatemala");
        flag.Add("Guernsey");
        flag.Add("Guinea");
        flag.Add("Guinea-Bissau");
        flag.Add("Guyana");
        flag.Add("Haiti");
        flag.Add("Heard Island and McDonald Islands");
        flag.Add("Honduras");
        flag.Add("Hong Kong");
        flag.Add("Hungary");
        flag.Add("Iceland");
        flag.Add("India");
        flag.Add("Indonesia");
        flag.Add("Iran");
        flag.Add("Iraq");
        flag.Add("Ireland");
        flag.Add("Isle of Man");
        flag.Add("Israel");
        flag.Add("Italy");
        flag.Add("Ivory Coast");
        flag.Add("Jamaica");
        flag.Add("Japan");
        flag.Add("Jersey");
        flag.Add("Jordan");
        flag.Add("Kazakhstan");
        flag.Add("Kenya");
        flag.Add("Kiribati");
        flag.Add("Kosovo");
        flag.Add("Kuwait");
        flag.Add("Kyrgyzstan");
        flag.Add("Laos");
        flag.Add("Latvia");
        flag.Add("Lebanon");
        flag.Add("Lesotho");
        flag.Add("Liberia");
        flag.Add("Libya");
        flag.Add("Liechtenstein");
        flag.Add("Lithuania");
        flag.Add("Luxembourg");
        flag.Add("Macao");
        flag.Add("Madagascar");
        flag.Add("Malawi");
        flag.Add("Malaysia");
        flag.Add("Mali");
        flag.Add("Malta");
        flag.Add("Marshall Islands");
        flag.Add("Martinique");
        flag.Add("Mauritania");
        flag.Add("Mauritius");
        flag.Add("Mayotte");
        flag.Add("Mexico");
        flag.Add("Moldova");
        flag.Add("Monaco");
        flag.Add("Mongolia");
        flag.Add("Montenegro");
        flag.Add("Montserrat");
        flag.Add("Morocco");
        flag.Add("Mozambique");
        flag.Add("Myanmar (Burma)");
        flag.Add("Namibia");
        flag.Add("Nauru");
        flag.Add("Nepal");
        flag.Add("New Caledonia");
        flag.Add("New Zealand");
        flag.Add("Nicaragua");
        flag.Add("Niger");
        flag.Add("Nigeria");
        flag.Add("Niue");
        flag.Add("Norfolk Island");
        flag.Add("North Korea");
        flag.Add("North Macedonia");
        flag.Add("Northern Ireland");
        flag.Add("Northern Mariana Islands");
        flag.Add("Norway");
        flag.Add("Oman");
        flag.Add("Pakistan");
        flag.Add("Palau");
        flag.Add("Palestine");
        flag.Add("Panama");
        flag.Add("Papua New Guinea");
        flag.Add("Paraguay");
        flag.Add("Peru");
        flag.Add("Pitcairn Islands");
        flag.Add("Poland");
        flag.Add("Portugal");
        flag.Add("Puerto Rico");
        flag.Add("Qatar");
        flag.Add("Republic of the Congo");
        flag.Add("Romania");
        flag.Add("Russia");
        flag.Add("Rwanda");
        flag.Add("Réunion");
        flag.Add("Saint Barthélemy");
        flag.Add("Saint Helena, Ascension and Tristan da Cunha");
        flag.Add("Saint Kitts and Nevis");
        flag.Add("Saint Lucia");
        flag.Add("Saint Martin");
        flag.Add("Saint Pierre and Miquelon");
        flag.Add("Saint Vincent and the Grenadines");
        flag.Add("Samoa");
        flag.Add("San Marino");
        flag.Add("Saudi Arabia");
        flag.Add("Scotland");
        flag.Add("Senegal");
        flag.Add("Serbia");
        flag.Add("Seychelles");
        flag.Add("Sierra Leone");
        flag.Add("Singapore");
        flag.Add("Sint Maarten");
        flag.Add("Slovakia");
        flag.Add("Slovenia");
        flag.Add("Solomon Islands");
        flag.Add("Somalia");
        flag.Add("South Africa");
        flag.Add("South Georgia and the South Sandwich Islands");
        flag.Add("South Korea");
        flag.Add("South Sudan");
        flag.Add("Spain");
        flag.Add("Sri Lanka");
        flag.Add("Sudan");
        flag.Add("Surinam");
        flag.Add("Svalbard and Jan Mayen");
        flag.Add("Swaziland (eSwatini)");
        flag.Add("Sweden");
        flag.Add("Switzerland");
        flag.Add("Syria");
        flag.Add("São Tomé and Príncipe");
        flag.Add("Taiwan");
        flag.Add("Tajikistan");
        flag.Add("Tanzania");
        flag.Add("Thailand");
        flag.Add("The Bahamas");
        flag.Add("the British Indian Ocean Territory");
        flag.Add("The Comoros");
        flag.Add("the Federated States of Micronesia");
        flag.Add("The Maldives");
        flag.Add("The Netherlands");
        flag.Add("The Philippines");
        flag.Add("Timor-Leste");
        flag.Add("Togo");
        flag.Add("Tokelau");
        flag.Add("Tonga");
        flag.Add("Trinidad and Tobago");
        flag.Add("Tunisia");
        flag.Add("Turkey");
        flag.Add("Turkmenistan");
        flag.Add("Turks and Caicos Islands");
        flag.Add("Tuvalu");
        flag.Add("U.S. Virgin Islands");
        flag.Add("Uganda");
        flag.Add("Ukraine");
        flag.Add("United Arab Emirates");
        flag.Add("United Kingdom");
        flag.Add("United States");
        flag.Add("Uruguay");
        flag.Add("Uzbekistan");
        flag.Add("Vanuatu");
        flag.Add("Vatican City");
        flag.Add("Venezuela");
        flag.Add("Vietnam");
        flag.Add("Virgin Islands");
        flag.Add("Wales");
        flag.Add("Wallis and Futuna");
        flag.Add("Western Sahara");
        flag.Add("Yemen");
        flag.Add("Zambia");
        flag.Add("Zimbabwe");
        flag.Add("Åland Islands");

    }
    

    // Update is called once per frame
    void Update()
    {
        
    }
}
